# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03f7f452fc1c3f546f253747f4fc1f467ef333febb4760d5ca22ac9465186e86c64abdc5e8bcefbfac7eaacdd9324c83bb2de087e1d4d438349fb8d4f99eebb6

test:
  secret_key_base: 48410089a504fb0a69b9c06b8020e481a02a56437a07b896ed07efd336d451d210841364b40d18f9fe799c88c10533296491180fbaacaaa9ef0f3b33c18a97fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
